const activities = [
    "Write a haiku", "Doodle on the corner of a page", "Try a new hairstyle", "Cook a recipe from a different culture", "Listen to a music genre you usually don't", "Watch a foreign film", "Read a book by an author from a different continent", "Go for a midnight walk", "Learn five phrases in a new language", "Plant a tree", "Make a homemade face mask", "Attend a local sports game", "Visit a garage sale", "Volunteer for a beach clean-up", "Go cloud watching", "Create a playlist of your favorite songs", "Send a postcard to a friend", "Bake cookies and share them with neighbors", "Start a mini herb garden", "Organize a small potluck dinner", "Attend a yoga class", "Watch a documentary on a topic you know little about", "Visit an escape room", "Take a bubble bath", "Paint rocks and leave them in the park for others to find", "Make a kite and fly it on a windy day", "Go fruit picking at a local farm", "Visit a senior home and spend time chatting", "Create a scrapbook of your last year", "Take a spontaneous road trip", "Donate blood", "Host a movie marathon with a theme", "Start a blog about a passion of yours", "Go to a pottery class", "Spend the day taking photos of your city", "Explore a part of town you've never been to", "Play tourist in your own city", "Go horseback riding", "Write letters to family members and mail them", "Spend an afternoon bird watching", "Attend a dance class", "Build a birdhouse", "Go fishing", "Learn a magic trick", "Watch the sunrise or sunset", "Learn to roller skate", "Try your hand at archery", "Go kayaking", "Join a book club", "Go vegan for a week", "Participate in a local theater production", "Do a DIY home decor project", "Make your own candles", "Try out geocaching", "Visit an art exhibit", "Attend a local music gig", "Learn to sew and make a simple garment", "Organize your digital photos", "Start a collection", "Attend a film festival", "Make a time capsule", "Learn to salsa dance", "Make homemade jam", "Create an obstacle course in your backyard", "Participate in a community garden", "Start a podcast", "Go bird watching", "Learn to play chess", "Participate in a scavenger hunt", "Try making sushi at home", "Attend a live comedy show", "Go on a ghost tour", "Make a family tree", "Learn origami", "Start a gratitude journal", "Go to a drive-in movie", "Refurbish an old piece of furniture", "Attend a DIY workshop", "Learn to mix cocktails", "Go ice skating", "Visit a planetarium", "Take a class on finance management", "Watch an opera performance", "Join a fantasy sports league", "Try pottery making", "Go on a picnic", "Take a fitness challenge", "Go bungee jumping", "Visit an animal sanctuary", "Host a board game night", "Attend a poetry reading", "Participate in a martial arts class", "Take a nap under a tree in a park", "Make homemade pasta", "Go snorkeling", "Create your own comic strip", "Make a video diary", "Build a model airplane", "Go ziplining", "Attend a VR gaming session"
];

function getRandomThing() {
    const randomIndex = Math.floor(Math.random() * activities.length);
    const selectedActivity = activities[randomIndex];

    document.getElementById("thing").textContent = selectedActivity;
}